name: SonarCloud security scan
description: SonarCloud security scan
inputs:
  github_token:
    description: 'token for github repository access'
    required: true
  sonar_token:
    description: 'token for sonar cloud access'
    required: true
runs:
  using: "composite"
  steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar_token }}