name: Generate Dora metrics
description: Generate Dora metrics
inputs:
  github_access_token:
    description: "authorization token"
    required: true
  branch:
    description: "repository branch"
    required: true
runs:
  using: "composite"
  steps:
    - name: 🛠️ Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: 🛠️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: ⬇️ Pull Docker image
      shell: bash
      run: docker pull abhimishraa/dorametrics:latest

    - name: ➕ Generate metrics
      shell: bash
      run: docker run --rm -v "$(pwd)/metrics":/app/metrics -v "$(pwd)/.git":/app/.git abhimishraa/dorametrics:latest --calculate-metrics -p ${{ inputs.branch }} -e True

    - name: 💻 Commit files
      shell: bash
      run: |
        git config --local user.email github-actions[bot]
        git config --local user.name github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "updated metrics insights [skip ci]"

    - name: 🚀 Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_access_token }}
        branch: ${{ inputs.branch }}