name: Trivy security testing infrastructure as code
description: Trivy security testing infrastructure as code
inputs:
  environment:
    description: 'environment to scan'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-ref: 'charts/${{ inputs.environment }}'
        scan-type: 'config'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        ignore-unfixed: false
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'